name: Integration

on:
  workflow_dispatch:

jobs:
  live-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - run: npm ci
      - run: npm run build
      - name: Live API integration tests
        env:
          TRUSS_API_KEY: ${{ secrets.TRUSS_API_KEY }}
          TRUSS_API_URL: https://api-test.truss-security.com
          TRUSS_RUN_INTEGRATION: '1'
        run: npm test
